### ISSUE TITLE
clear outdated correlation data

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla/stab-crashes#36]
when a crash decreases in frequency, so that no new correlations get generated for the signature, the prior data remains in place on https://mozilla.github.io/stab-crashes/correlations.html and socorro. as this outdated data may be misleading, maybe it's better to generally purge the old correlations...

(current sample: https://mozilla.github.io/stab-crashes/correlations.html?product=Firefox&channel=beta&signature=nsFrame::BoxReflow points to a correlation with a particular theme, but it was already fixed a few weeks back and the crashes declined after that)

**Comment by marco-c** [comment]
This will be fixed starting tomorrow (https://github.com/marco-c/crashcorrelations/commit/644a3842e54f94aa51e89edaa00d052158e70e78).
