### ISSUE TITLE
Missing uplifts panel not showing results

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla/stab-crashes#41]
the dashboard at https://mozilla.github.io/stab-crashes/all_missing_uplifts.html is constantly loading. 

the network monitor is showing a 400 Bad Request error code connecting to 
https://bugzilla.mozilla.org/rest/bug?f1=cf_crash_signature&o1=isnotempty&j2=AND&f2=OP&f3=cf_status_firefox56&o3=notequals&v3=fixed&f4=cf_status_firefox56&o4=notequals&v4=verified&f5=cf_status_firefox56&o5=notequals&v5=unaffected&f6=cf_status_firefox56&o6=notequals&v6=wontfix&f7=CP&j8=OR&f8=OP&j9=OR&f9=OP&f10=cf_status_firefox57&o10=equals&v10=verified&f11=cf_status_firefox57&o11=equals&v11=fixed&f12=CP&j13=OR&f13=OP&f14=cf_status_firefox58&o14=equals&v14=verified&f15=cf_status_firefox58&o15=equals&v15=fixed&f16=CP&f17=CP&include_fields=id,last_change_time,cf_crash_signature,cf_status_firefox56,cf_status_firefox57,cf_status_firefox58 - the page shows an error "Can't use cf_status_firefox58 as a field name." when manually loading it.

**Comment by marco-c** [comment]
Thanks, it should be fixed now (the deployment should take just a few minutes).
