### ISSUE TITLE
Missing uplifts panel stopped showing results recently

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla/stab-crashes#44]
The dashboard at https://mozilla.github.io/stab-crashes/all_missing_uplifts.html is showing the loading animation continually at the moment without getting to a result.

the web console shows the following error:
![grafik](https://user-images.githubusercontent.com/1524147/42104180-f218ed8a-7bcb-11e8-9186-f98463d4ed22.png)

**Comment by philipp-sumo** [comment]
and it's due to bug 1470746 which is in the list of processed data, which doesn't have a signature associated with it (it got moved in bugzilla from toolkit -> webextensions, where the signature field got stripped).

**Comment by marco-c** [comment]
@philipp-sumo it's working now. Do you know why the signature was stripped?

**Comment by philipp-sumo** [comment]
> Do you know why the signature was stripped?
looking into that via https://bugzilla.mozilla.org/show_bug.cgi?id=1473726
