### ISSUE TITLE
Some breakage due to removal of socorro's ProductVersions API endpoint

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla/stab-crashes#46]
https://bugzilla.mozilla.org/show_bug.cgi?id=1496580 removed the ProductVersions API endpoint which is causing some breakage with various tools here:
https://mozilla.github.io/stab-crashes/all_missing_uplifts.html
https://mozilla.github.io/stab-crashes/beta-stability-pushlog.html
https://mozilla.github.io/stab-crashes/compare-betas.html

**Comment by marco-c** [comment]
Thanks for the report, @philipp-sumo. 47c54d5 is fixing all_missing_uplifts.html.

**Comment by marco-c** [comment]
Fixing the other two will likely require replacing ProductVersions with buildhub.

**Comment by marco-c** [comment]
aed4a6d fixed compare-betas.html (but we don't have RCs anymore now).

**Comment by marco-c** [comment]
ed9f9d9f9306eadd83c1b37c45da158c30213c8b fixed the last remaining issue.
