### ISSUE TITLE
Super Search Comparison is broken by crash-stats.mozilla.com CORS errors

### ISSUE THREAD

**Issue by cpeterso** [mozilla/stab-crashes#53]
This Super Search Comparison query has worked fine for months and as recently as last week: 

https://mozilla.github.io/stab-crashes/scomp.html?common=product%3DFirefox&p1=channel%3Dnightly&p2=channel%3Dnightly%26dom_fission_enabled%3D1

But today it fails with "ERROR: XHR status 0" and some suspicious CORS errors in the web console: 

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://crash-stats.mozilla.com/api/SuperSearch/?_facets=sig…ts_number=0&product=Firefox&channel=nightly&_facets_size=300. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://crash-stats.mozilla.com/api/SuperSearch/?_facets=sig…ts_number=0&product=Firefox&channel=nightly&_facets_size=300. (Reason: CORS request did not succeed).

ERROR: XHR status 0 - https://crash-stats.mozilla.com/api/SuperSearch/?_facets=signature&_results_number=0&product=Firefox&channel=nightly&_facets_size=300 scomp.js:308:15
```

willkg says: "we put in the redirect from [crash-stats.mozilla].COM to .ORG today. i think you're hitting that. try using crash-stats.mozilla.org and see if that fixes your issue."

I think stab-crashes' references to `https://crash-stats.mozilla.com/` need to be changed to `https://crash-stats.mozilla.org/`.

**Comment by marco-c** [comment]
Thanks, I've updated the URLs.

**Comment by cpeterso** [comment]
@marco-c - I still see crash-stats.mozilla.com URLs on Super Search Comparison site (e.g. https://mozilla.github.io/stab-crashes/scomp.html?common=product%3DFirefox&p1=channel%3Dnightly&p2=channel%3Dnightly%26dom_fission_enabled%3D1).

Is an extra step needed to deploy the scomp.js changes from https://github.com/mozilla/stab-crashes/blob/master/scomp.js to the https://mozilla.github.io/stab-crashes/scomp.js?

**Comment by marco-c** [comment]
The Travis had build failed (error connecting to Bugzilla) and Travis didn't notify me of the failure... It's deployed now.

**Comment by cpeterso** [comment]
The Super Search Comparison works now. Thanks! 🎉
